# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Firebase Distribution"
    lane :firebase do
        # build_ios_app(...)
        build_app(workspace: "AwesomeProject2.xcworkspace", scheme: "AwesomeProject2")
        # build_ios_app is a built-in fastlane action.

        firebase_app_distribution(
            app: "1:298941541312:ios:70c7b63e4bf0f33aa57625",
            # groups: "devs,qa",# qa, managers
            # release_notes: File.read("../../release-notes.txt"),
        )

    end

end


