# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Firebase distribution"
    lane :firebase do
        # build_android_app(task: "bundle", ...)
        # build_android_app is a built-in fastlane action.
        gradle(task: "clean assembleRelease")

        firebase_app_distribution(
            app: "1:298941541312:android:ed3af6bba340151fa57625",
            # groups: "devs,qa",# qa, managers
            # release_notes: File.read("../../release-notes.txt"),
            android_artifact_type: "APK"
        )
    end
end



#1:298941541312:android:ed3af6bba340151fa57625